import fs from "node:fs/promises";
import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";

const sourcePath = "C:/Users/charl/OneDrive/Desktop/bbsgame/data/GameContent_Perks_Worldbosses.xlsx";
const workbook = await SpreadsheetFile.importXlsx(await FileBlob.load(sourcePath));

const scenesRows = [
  ["TOTALRECALL_REACTOR_UPRISING","Total Recall","Reactor Uprising","Mars is choking under sealed domes while the ancient reactor waits beneath the colony. Douglas Quaid races toward the controls as Vilos Cohaagen seals the chamber and draws his sidearm.","Douglas Quaid","BOSS","Vilos Cohaagen",2,8,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,145,65,true,"Boss Scene at the Martian reactor."],
  ["STARTREKVI_CLOAKED_ASSAULT","Star Trek VI: The Undiscovered Country","The Cloaked Assault","Torpedo impacts shake the ship while an invisible attacker circles beyond the viewscreen. James T. Kirk prepares a counterattack as General Chang decloaks for the killing blow.","James T. Kirk","BOSS","General Chang",2,8,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,145,65,true,"Starship crisis translated into an allied boss confrontation."],
  ["THREEHUNDRED_HOTGATES","300","Last Stand at the Hot Gates","Dust and arrows darken the narrow pass. Leonidas plants his shield beside you as Xerxes enters the battlefield beneath a canopy of gold and blades.","Leonidas","BOSS","Xerxes",2,9,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,155,70,true,"A direct final stand against the God-King."],
  ["T2_STEEL_MILL","Terminator 2: Judgment Day","Steel Mill Pursuit","Molten metal paints the steel mill orange as machinery pounds around you. Sarah Connor searches for a clear shot while the T-1000 reforms between the catwalks.","Sarah Connor","BOSS","T-1000",2,9,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,155,70,true,"Industrial confrontation with the liquid-metal assassin."],
  ["TWOTOWERS_ORTHANC","The Lord of the Rings: The Two Towers","The Voice of Orthanc","Storm clouds coil around the black tower while machinery burns below. Aragorn approaches the shattered gate as Saruman the White raises his staff above the balcony.","Aragorn","BOSS","Saruman the White",2,10,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,165,75,true,"Siege aftermath and sorcerous boss confrontation."],
  ["MATRIX_SUBWAY_SHOWDOWN","The Matrix","Subway Showdown","The last train has gone and the platform lights flicker. Neo turns away from the exit as Agent Smith steps from the shadows and seals the station.","Neo","BOSS","Agent Smith",2,10,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,165,75,true,"Reality-bending confrontation in a closed subway station."],
  ["GLADIATOR_ARENA_BETRAYAL","Gladiator","The Emperor Enters the Arena","The crowd falls silent as the imperial gate opens. Maximus raises his sword while Commodus enters the sand behind polished armor and hidden treachery.","Maximus","BOSS","Commodus",2,11,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,175,80,true,"Arena duel with an armed protagonist ally."],
  ["THING_BLOOD_TEST","The Thing","Blood Test Breakdown","Wind hammers Outpost 31 while the generator sputters. MacReady holds a heated wire above the final sample as The Thing tears free from its failing disguise.","MacReady","BOSS","The Thing",2,11,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,175,80,true,"Paranoia becomes open combat inside the Antarctic outpost."],
  ["EMPIRE_CARBON_CHAMBER","Star Wars: The Empire Strikes Back","The Carbon Chamber","Steam floods the chamber and orange light rises from the freezing pit. Luke Skywalker ignites his weapon as Darth Vader descends the stairs to meet him.","Luke Skywalker","BOSS","Darth Vader",2,12,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,185,85,true,"High-level duel amid machinery and exposed platforms."],
  ["FLASHGORDON_THRONE_REVOLT","Flash Gordon","Revolt in the Throne Room","War rockets shake the imperial palace as rival banners fill the sky. Flash Gordon charges the dais while Ming the Merciless raises his sceptre over the throne room.","Flash Gordon","BOSS","Ming the Merciless",2,12,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,185,85,true,"Colorful palace uprising against Ming."],
  ["WILLOW_NOCKMAAR_RITUAL","Willow","The Nockmaar Ritual","Black clouds turn above the fortress as the ritual chamber fills with unnatural wind. Willow Ufgood grips his wand while Bavmorda begins the final incantation.","Willow Ufgood","BOSS","Bavmorda",2,13,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,195,90,true,"Magical confrontation inside Nockmaar."],
  ["LABYRINTH_ESCHER_STAIRS","Labyrinth","The Impossible Stairway","Staircases fold through gravity in every direction while the castle clock advances. Sarah Williams follows the correct horizon as Jareth scatters crystal illusions across her path.","Sarah Williams","BOSS","Jareth",2,13,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,195,90,true,"Surreal confrontation within the shifting castle."],
  ["TRON_MCP_CORE","Tron","Assault on the MCP Core","Red circuitry races across the walls as the core closes every access channel. Kevin Flynn reaches the central platform while the MCP focuses its beam upon him.","Kevin Flynn","BOSS","MCP",2,14,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,205,95,true,"Digital boss confrontation at the system core."],
  ["ARMYDARKNESS_CASTLE_SIEGE","Army of Darkness","Siege of the Living","Deadites pour over the castle walls beneath a storm of flaming debris. Ash Williams levels his boomstick as Evil Ash climbs onto the battlements.","Ash Williams","BOSS","Evil Ash",2,14,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,205,95,true,"Chaotic medieval siege against the Deadite commander."],
  ["STARGATE_PYRAMID_REVOLT","Stargate","Revolt Beneath the Pyramid","Sand whips across the landing platform as the pyramid seals its great doors. Daniel Jackson deciphers the final controls while Ra descends in the armor of a false god.","Daniel Jackson","BOSS","Ra",2,15,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,215,100,true,"Rebellion and alien technology converge beneath the pyramid."],
  ["EXCALIBUR_CHARM_MAKING","Excalibur","The Charm of Making","Mist coils through a ruined hall where banners hang in tatters. King Arthur raises Excalibur while Morgana shapes the old words into a weapon.","King Arthur","BOSS","Morgana",2,15,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,215,100,true,"Mythic confrontation of kingship and sorcery."],
  ["DUNE_GIEDI_ARENA","Dune 2021","Champion of the Black Sun","Black fireworks bloom above the arena as the crowd chants from stone terraces. Paul Atreides enters beside you while Feyd-Rautha tests the edge of a poisoned blade.","Paul Atreides","BOSS","Feyd-Rautha",2,16,4,"DEFEAT_ENEMY","ATTACK_ONLY","THREAT_WEIGHTED",false,0.10,0.06,225,105,true,"Late-game arena Scene against the Harkonnen champion."],
];

const c = (scene, key, attr, text, difficulty, success, failure, xp, credits, successEffect, successValue, failureValue, rewardMod, notes) =>
  [scene,key,attr,text,difficulty,success,failure,xp,credits,successEffect,successValue,"COMBAT",failureValue,true,rewardMod,notes];

const choicesRows = [
  c("TOTALRECALL_REACTOR_UPRISING","FORCE_VALVE","STR","Force the ancient reactor valve open before the chamber locks down.",17,"The mechanism turns and pressure tears away Cohaagen's cover.","The valve jams and Cohaagen reaches the firing platform first.",72,30,"ENEMY_DEBUFF",1,0,0.02,"Physical reactor control."),
  c("TOTALRECALL_REACTOR_UPRISING","CROSS_THIN_AIR","END","Cross the depressurized gallery while Quaid restores the atmosphere.",16,"You endure the thin air and secure the far door for Quaid.","Your strength fades halfway across and Cohaagen opens fire.",70,30,"ALLY_BUFF",2,5,0,"Endurance route with opening damage on failure."),
  c("TOTALRECALL_REACTOR_UPRISING","SLIDE_CONDUIT","AGI","Slide beneath the moving reactor rings and reach the control dais.",15,"You clear the machinery and force Cohaagen to turn from Quaid.","A rotating ring clips your path and announces the attack.",68,32,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("TOTALRECALL_REACTOR_UPRISING","PRESS_MEMORY","LCK","Press an unfamiliar memory-marked control and trust Quaid's instincts.",19,"The system recognizes the sequence and opens the core.","The control activates a defense grid around Cohaagen.",84,38,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk memory gamble."),
  c("TOTALRECALL_REACTOR_UPRISING","READ_HOLOGRAM","PER","Study the alien hologram and identify the true atmosphere controls.",14,"You isolate the correct sequence and expose Cohaagen's position.","A mirrored projection leads you to a dead control bank.",70,31,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("STARTREKVI_CLOAKED_ASSAULT","BRACE_CONSOLE","STR","Hold the weapons console steady through the next torpedo impact.",16,"The console stays online and Kirk returns fire before Chang can cloak.","The mount tears free and Chang gains another firing pass.",72,30,"FIRST_STRIKE",1,0,0.02,"Strength preserves the firing solution."),
  c("STARTREKVI_CLOAKED_ASSAULT","SEAL_BULKHEAD","END","Hold the ruptured bulkhead while the emergency field initializes.",16,"The deck remains pressurized and Kirk keeps command of the counterattack.","The field flickers and the blast throws you across the bridge.",70,30,"ALLY_BUFF",2,5,0,"Endurance protection."),
  c("STARTREKVI_CLOAKED_ASSAULT","REACH_AUXILIARY","AGI","Cross the damaged bridge and reroute targeting through auxiliary control.",15,"You restore the targeting feed before Chang completes his turn.","Falling debris blocks the console and exposes your movement.",68,32,"COMBAT_ADVANTAGE",1,0,0.03,"Agility route."),
  c("STARTREKVI_CLOAKED_ASSAULT","FIRE_BLIND","LCK","Launch a torpedo into empty space and gamble on Chang's attack vector.",19,"The torpedo catches the cloaked ship crossing its path.","The shot passes harmlessly through space and reveals your timing.",84,38,"ENEMY_DEBUFF",2,0,0.07,"High-risk tactical gamble."),
  c("STARTREKVI_CLOAKED_ASSAULT","TRACE_EXHAUST","PER","Search the sensor noise for ionized exhaust from the cloaked ship.",14,"A faint trail reveals Chang's exact approach.","A damaged engine produces a convincing false return.",70,31,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("THREEHUNDRED_HOTGATES","CLOSE_RANKS","STR","Drive your shield into the line and close the gap beside Leonidas.",18,"The wall locks together and forces Xerxes into the narrow ground.","The impact opens the formation and Xerxes attacks through it.",78,32,"ENEMY_DEBUFF",1,0,0.02,"Formation strength."),
  c("THREEHUNDRED_HOTGATES","WITHSTAND_VOLLEY","END","Stand beneath the arrow storm while Leonidas advances.",17,"You endure the volley and keep the path open.","The weight of the barrage breaks your stance.",76,32,"ALLY_BUFF",2,6,0,"Endurance defense."),
  c("THREEHUNDRED_HOTGATES","CLIMB_CLIFF","AGI","Scale the pass wall and descend behind Xerxes's guard.",16,"You reach the ledge and divide the imperial formation.","Loose stone gives away your climb.",74,34,"FIRST_STRIKE",1,0,0.03,"Agility flanking route."),
  c("THREEHUNDRED_HOTGATES","CAST_BROKEN_SPEAR","LCK","Cast a broken spear through the dust and trust its path.",20,"The spear tears through the royal canopy and strips away Xerxes's certainty.","The weapon vanishes into the dust without effect.",90,40,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk throw."),
  c("THREEHUNDRED_HOTGATES","READ_FORMATION","PER","Study the imperial ranks and identify the moment their shields separate.",15,"You call the opening and Leonidas strikes through it.","A ceremonial movement disguises the true attack.",76,33,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("T2_STEEL_MILL","DROP_BEAM","STR","Tear loose a suspended beam and drop it across the T-1000's path.",18,"The beam pins the liquid-metal frame long enough for Sarah to aim.","The support breaks early and the T-1000 flows around it.",78,32,"ENEMY_DEBUFF",1,0,0.02,"Industrial strength."),
  c("T2_STEEL_MILL","CROSS_HEAT","END","Cross the furnace platform despite the punishing heat.",17,"You reach the controls and keep Sarah clear of the molten channel.","The heat drives you back into the T-1000's reach.",76,32,"ALLY_BUFF",2,6,0,"Endurance route."),
  c("T2_STEEL_MILL","SWING_CHAIN","AGI","Swing from the hoist chain and land behind the T-1000.",16,"You reach the far platform before it can reform.","The chain slips and drops you into its view.",74,34,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("T2_STEEL_MILL","OPEN_RANDOM_LADLE","LCK","Release an unlabeled foundry control and gamble on the molten flow.",20,"Molten metal floods the correct channel and cuts off the T-1000.","The wrong ladle pours across your escape route.",90,40,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk machinery gamble."),
  c("T2_STEEL_MILL","TRACK_REFLECTION","PER","Watch the polished machinery for liquid-metal reflections.",15,"The distorted image reveals where the T-1000 is reforming.","Furnace glare creates a false shape behind you.",76,33,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("TWOTOWERS_ORTHANC","BREAK_GATE","STR","Break the warped inner gate before Saruman seals the tower.",19,"The gate yields and Aragorn gains a clear approach.","The gate holds and Saruman turns his staff toward you.",84,35,"FIRST_STRIKE",1,0,0.02,"Forceful entry."),
  c("TWOTOWERS_ORTHANC","ENDURE_VOICE","END","Resist Saruman's commanding voice and keep Aragorn focused.",18,"You hold to your purpose and break the spell's rhythm.","The voice weighs upon your will and slows your defense.",82,35,"ALLY_BUFF",2,6,0,"Endurance against sorcery."),
  c("TWOTOWERS_ORTHANC","CLIMB_RUIN","AGI","Climb the broken machinery and reach the tower stair.",17,"You gain the stair before Saruman can collapse it.","A gear shifts beneath you and gives away the route.",80,37,"COMBAT_ADVANTAGE",1,0,0.03,"Agility route."),
  c("TWOTOWERS_ORTHANC","CAST_STONE","LCK","Cast a loose stone toward the balcony and trust the storm wind.",20,"The wind carries it into the mechanism supporting Saruman's platform.","The stone falls short and marks your position.",94,43,"ENEMY_DEBUFF",2,0,0.07,"Risky wind-assisted attack."),
  c("TWOTOWERS_ORTHANC","READ_RUNES","PER","Read the carved runes around the tower base for a weakness in the ward.",16,"You find the broken sequence and open a path through the defense.","A false rune triggers Saruman's attention.",82,36,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("MATRIX_SUBWAY_SHOWDOWN","BEND_PILLAR","STR","Rip a steel signpost free and drive Smith away from the exit.",19,"The blow forces Smith into Neo's firing line.","Smith catches the weapon and closes the distance.",84,35,"ENEMY_DEBUFF",1,0,0.02,"Physical manipulation of the simulation."),
  c("MATRIX_SUBWAY_SHOWDOWN","IGNORE_WOUND","END","Ignore the simulation's pain and hold Smith's attention.",18,"You remain standing and give Neo time to reposition.","The false pain becomes real enough to break your guard.",82,35,"ALLY_BUFF",2,6,0,"Endurance of mind and body."),
  c("MATRIX_SUBWAY_SHOWDOWN","RUN_WALL","AGI","Run along the tiled wall and cross Smith's firing angle.",16,"You land behind Smith before the simulation corrects itself.","Gravity reasserts itself one step too early.",80,37,"FIRST_STRIKE",1,0,0.03,"Agility is favored."),
  c("MATRIX_SUBWAY_SHOWDOWN","TAKE_RED_DOOR","LCK","Enter an unmarked service door and trust that the Matrix leads behind Smith.",20,"The door opens onto the opposite platform at the perfect moment.","It returns you to the same platform in Smith's sights.",94,43,"COMBAT_ADVANTAGE",2,0,0.07,"Reality gamble."),
  c("MATRIX_SUBWAY_SHOWDOWN","SEE_CODE","PER","Look past the station surfaces and follow the errors in the code.",15,"Smith's next position flickers into view before he moves.","The code fills with deliberate decoys.",82,36,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("GLADIATOR_ARENA_BETRAYAL","BREAK_SHIELD","STR","Split the imperial shield before Commodus can hide behind it.",19,"The shield breaks and Maximus presses the exposed flank.","The blade catches and Commodus counters through the opening.",90,38,"ENEMY_DEBUFF",1,0,0.02,"Arena strength."),
  c("GLADIATOR_ARENA_BETRAYAL","FIGHT_WOUNDED","END","Ignore the hidden wound and hold the center beside Maximus.",18,"You endure and deny Commodus the advantage he expected.","The strain reveals your weakness and invites his attack.",88,38,"ALLY_BUFF",2,7,0,"Endurance route."),
  c("GLADIATOR_ARENA_BETRAYAL","ROLL_NET","AGI","Roll beneath a cast arena net and attack from its far side.",17,"You clear the net and turn Commodus toward Maximus.","The weighted edge catches your ankle.",86,40,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("GLADIATOR_ARENA_BETRAYAL","KICK_SAND","LCK","Kick a cloud of arena sand and gamble on the wind.",21,"The sand blinds Commodus without touching Maximus.","The wind carries it back across your own vision.",100,46,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk arena trick."),
  c("GLADIATOR_ARENA_BETRAYAL","READ_CROWD","PER","Use the crowd's reaction to track Commodus behind the glare.",16,"The rising noise warns you of his concealed strike.","The crowd responds to a feint and misleads you.",88,39,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("THING_BLOOD_TEST","PIN_TABLE","STR","Pin the testing table as the imitation erupts from its restraints.",19,"You hold it long enough for MacReady to bring the flame.","The table tears free and the creature expands across the room.",90,38,"ENEMY_DEBUFF",1,0,0.02,"Containment strength."),
  c("THING_BLOOD_TEST","WITHSTAND_COLD","END","Cross the frozen corridor without slowing while MacReady covers you.",18,"You reach the fuel controls and keep the creature contained.","The cold numbs your hands before the controls respond.",88,38,"ALLY_BUFF",2,7,0,"Antarctic endurance."),
  c("THING_BLOOD_TEST","DODGE_TENTACLE","AGI","Slip beneath the first tentacle and reach the flamethrower fuel.",17,"You reach the canister before the creature blocks it.","A second limb anticipates your movement.",86,40,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("THING_BLOOD_TEST","TEST_LAST_SAMPLE","LCK","Heat the final unlabeled sample and gamble that it belongs to the imitation.",21,"The sample recoils and reveals the creature's hidden mass.","The sample is clean and the true creature attacks behind you.",100,46,"COMBAT_ADVANTAGE",2,0,0.07,"Paranoia gamble."),
  c("THING_BLOOD_TEST","COMPARE_BEHAVIOR","PER","Compare every crewman's movements with the blood reactions.",16,"A tiny synchronized flinch reveals the imitation.","Fear makes an innocent movement look inhuman.",88,39,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("EMPIRE_CARBON_CHAMBER","JAM_PLATFORM","STR","Jam the moving platform before Vader controls the distance.",20,"The platform locks and gives Luke stable ground.","The mechanism crushes the brace and Vader advances.",96,40,"ENEMY_DEBUFF",1,0,0.02,"Mechanical strength."),
  c("EMPIRE_CARBON_CHAMBER","RESIST_FORCE","END","Stand against the crushing pressure and keep Luke on his feet.",19,"You endure the pressure and break Vader's rhythm.","The invisible force drives you against the chamber wall.",94,40,"ALLY_BUFF",2,7,0,"Endurance against the Force."),
  c("EMPIRE_CARBON_CHAMBER","LEAP_CATWALK","AGI","Leap between the narrow catwalks and approach from above.",18,"You land beyond Vader's guard and divide his attention.","The catwalk drops under your landing.",92,42,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("EMPIRE_CARBON_CHAMBER","CUT_STEAM","LCK","Cut one steam line and gamble on where the pressure erupts.",22,"The blast obscures Vader while leaving Luke a clear lane.","The steam erupts across your own platform.",106,48,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk environmental gamble."),
  c("EMPIRE_CARBON_CHAMBER","SENSE_TRAP","PER","Watch Vader's stillness and identify the machinery he intends to use.",17,"You warn Luke before the chamber activates.","Vader's feint draws your attention from the true attack.",94,41,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("FLASHGORDON_THRONE_REVOLT","TOPPLE_STANDARD","STR","Topple an imperial standard across Ming's guard line.",20,"The heavy frame scatters the guards and opens the dais.","The standard catches on its chain and swings back toward you.",96,40,"ENEMY_DEBUFF",1,0,0.02,"Palace strength."),
  c("FLASHGORDON_THRONE_REVOLT","CROSS_ROCKET_FIRE","END","Advance through the palace bombardment while Flash covers the stairs.",19,"You endure the impacts and reach the throne beside Flash.","The concussive blasts halt your advance.",94,40,"ALLY_BUFF",2,7,0,"Endurance route."),
  c("FLASHGORDON_THRONE_REVOLT","SWING_BANNER","AGI","Swing from a hanging banner and land behind the imperial throne.",18,"You land cleanly and force Ming to split his attention.","The banner tears before you clear the guard rail.",92,42,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("FLASHGORDON_THRONE_REVOLT","PRESS_GOLD_CONTROL","LCK","Press a jeweled control and gamble that it lowers the throne shield.",22,"The shield collapses and exposes Ming's position.","The control seals the dais behind an energy wall.",106,48,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk palace technology."),
  c("FLASHGORDON_THRONE_REVOLT","READ_COURT","PER","Watch the courtiers and identify which passage Ming expects to use.",17,"Their fear reveals the hidden royal escape.","A loyal courtier deliberately points you toward a trap.",94,41,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("WILLOW_NOCKMAAR_RITUAL","MOVE_ALTAR","STR","Shift the stone altar out of Bavmorda's ritual circle.",21,"The circle breaks and Willow gains a clear spell line.","The altar locks into the floor and Bavmorda completes another phrase.",102,43,"ENEMY_DEBUFF",1,0,0.02,"Physical disruption of magic."),
  c("WILLOW_NOCKMAAR_RITUAL","ENDURE_CURSE","END","Stand within the ritual wind and keep Willow from being driven back.",20,"You withstand the curse and anchor Willow's casting.","The magic tears through your defense.",100,43,"ALLY_BUFF",2,8,0,"Endurance against sorcery."),
  c("WILLOW_NOCKMAAR_RITUAL","CROSS_BEAMS","AGI","Cross the narrow rafters above the ritual chamber.",19,"You reach the hanging focus and cut it free.","A beam twists and drops you into Bavmorda's sight.",98,45,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("WILLOW_NOCKMAAR_RITUAL","CAST_ACORN","LCK","Throw the enchanted acorn and trust that it reaches the true target.",22,"The magic catches the ritual focus and turns it to stone.","The acorn strikes an illusion and disappears.",112,51,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk magical gamble."),
  c("WILLOW_NOCKMAAR_RITUAL","READ_CIRCLE","PER","Study the ritual circle and find the symbol sustaining Bavmorda's spell.",18,"You identify the binding mark and direct Willow's counterspell.","A mirrored symbol draws you toward the wrong edge.",100,44,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("LABYRINTH_ESCHER_STAIRS","TURN_STAIR","STR","Force a rotating stairway into alignment with Sarah's path.",21,"The stair locks and creates a direct route toward Jareth.","The structure twists free and deposits you below him.",102,43,"ENEMY_DEBUFF",1,0,0.02,"Physical control of an impossible space."),
  c("LABYRINTH_ESCHER_STAIRS","IGNORE_VERTIGO","END","Walk the inverted stair without yielding to the impossible horizon.",20,"You keep your balance and guide Sarah across.","Vertigo breaks your focus and Jareth gains the advantage.",100,43,"ALLY_BUFF",2,8,0,"Endurance of perception."),
  c("LABYRINTH_ESCHER_STAIRS","LEAP_GRAVITY","AGI","Leap between two stairways as gravity changes direction.",19,"You land on Jareth's level and block his retreat.","Gravity reverses before your feet find the next step.",98,45,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("LABYRINTH_ESCHER_STAIRS","CHOOSE_ORB","LCK","Break one floating crystal and gamble that it contains the true path.",22,"The illusion collapses and reveals Jareth behind it.","The crystal releases another maze around you.",112,51,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk illusion gamble."),
  c("LABYRINTH_ESCHER_STAIRS","FOLLOW_SHADOW","PER","Ignore the stairways and follow the direction of Jareth's shadow.",18,"The shadow obeys real light and exposes his position.","The shadow moves independently and leads you astray.",100,44,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("TRON_MCP_CORE","BREAK_CONDUIT","STR","Tear an energy conduit from the core and interrupt the MCP beam.",22,"The severed circuit dims the beam and opens Flynn's route.","The conduit hardens into a defensive barrier.",108,46,"ENEMY_DEBUFF",1,0,0.02,"Digital strength."),
  c("TRON_MCP_CORE","ABSORB_SURGE","END","Take the system surge while Flynn reaches the override channel.",21,"You remain coherent and keep the channel open.","The surge fragments your defenses.",106,46,"ALLY_BUFF",2,8,0,"Endurance in the system."),
  c("TRON_MCP_CORE","RIDE_LIGHTLINE","AGI","Ride a moving lightline across the core defenses.",20,"You reach the central ring before the MCP redirects it.","The line turns beneath you and feeds into the beam.",104,48,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("TRON_MCP_CORE","ENTER_UNKNOWN_PORT","LCK","Enter an undocumented port and gamble that it reaches the core.",23,"The forgotten route bypasses the MCP firewall.","The port loops directly into a security process.",118,54,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk system gamble."),
  c("TRON_MCP_CORE","TRACE_PACKET","PER","Follow a privileged command packet back to the MCP core.",19,"The packet reveals the beam's control sequence.","The MCP injects a false command into the stream.",106,47,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("ARMYDARKNESS_CASTLE_SIEGE","DROP_CAULDRON","STR","Tip the castle cauldron onto the ladder beneath Evil Ash.",22,"The impact clears the wall and throws Evil Ash into Ash's sights.","The cauldron catches on its chain and leaves the wall exposed.",108,46,"ENEMY_DEBUFF",1,0,0.02,"Siege strength."),
  c("ARMYDARKNESS_CASTLE_SIEGE","HOLD_GATE","END","Hold the splintering gate while Ash reloads his boomstick.",21,"You keep the Deadites outside long enough for Ash to fire.","The gate buckles and drives you backward.",106,46,"ALLY_BUFF",2,8,0,"Endurance defense."),
  c("ARMYDARKNESS_CASTLE_SIEGE","SWING_ROPE","AGI","Swing from the siege rope and land on Evil Ash's platform.",20,"You land beside him and split his attention.","A Deadite cuts the rope midway through the swing.",104,48,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("ARMYDARKNESS_CASTLE_SIEGE","LIGHT_POWDER","LCK","Light an unmeasured powder charge and gamble on the fuse.",23,"The blast destroys Evil Ash's cover without breaching the wall.","The fuse races toward you faster than expected.",118,54,"COMBAT_ADVANTAGE",2,0,0.07,"Explosive gamble."),
  c("ARMYDARKNESS_CASTLE_SIEGE","SPOT_REAL_ASH","PER","Study the chaos and distinguish Evil Ash from his armored doubles.",19,"You identify the commander and direct Ash's shot.","A decoy mimics every gesture and draws your attack.",106,47,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("STARGATE_PYRAMID_REVOLT","LIFT_SEAL","STR","Lift the descending stone seal before Ra closes the inner chamber.",23,"The seal holds and Daniel enters with you.","The mechanism overpowers you and Ra attacks through the narrowing gap.",114,48,"FIRST_STRIKE",1,0,0.02,"Pyramid mechanism strength."),
  c("STARGATE_PYRAMID_REVOLT","ENDURE_STAFF_FIRE","END","Cross the landing platform under sustained staff fire.",22,"You endure the barrage and keep Daniel protected.","The final blast breaks your advance.",112,48,"ALLY_BUFF",2,9,0,"Endurance route."),
  c("STARGATE_PYRAMID_REVOLT","CLIMB_SARCOPHAGUS","AGI","Climb the sarcophagus machinery and reach Ra's upper platform.",21,"You clear the moving rings and attack from above.","The machinery activates and throws you into view.",110,50,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("STARGATE_PYRAMID_REVOLT","PRESS_GLYPH","LCK","Press an untranslated glyph and gamble that it disables Ra's shield.",24,"The shield flickers out and exposes the false god.","The glyph activates a guardian system around him.",124,56,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk alien technology."),
  c("STARGATE_PYRAMID_REVOLT","TRANSLATE_RING","PER","Compare the rotating symbols and identify the command controlling Ra's platform.",20,"You call the correct sequence and Daniel triggers it.","A ceremonial sequence disguises the real command.",112,49,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("EXCALIBUR_CHARM_MAKING","BREAK_MIRROR","STR","Shatter the black mirror focusing Morgana's spell.",23,"The mirror breaks and Arthur advances through the fading magic.","The reflection hardens and turns the force back upon you.",114,48,"ENEMY_DEBUFF",1,0,0.02,"Strength against a magical focus."),
  c("EXCALIBUR_CHARM_MAKING","WITHSTAND_CHARM","END","Stand against the Charm of Making and keep Arthur anchored to the hall.",22,"You endure the ancient words and preserve Arthur's strength.","The spell bends your senses and opens your defense.",112,48,"ALLY_BUFF",2,9,0,"Endurance against ancient magic."),
  c("EXCALIBUR_CHARM_MAKING","CROSS_FALLEN_ARCH","AGI","Cross the fallen arch above Morgana's ritual floor.",21,"You descend behind her wards and divide her attention.","The stones shift and cast you into the ritual light.",110,50,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("EXCALIBUR_CHARM_MAKING","RAISE_GRAIL","LCK","Raise the Grail into the spell and trust the old powers to oppose each other.",24,"The spell fractures around the Grail and exposes Morgana.","The competing powers erupt across the hall.",124,56,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk mythic gamble."),
  c("EXCALIBUR_CHARM_MAKING","READ_ECHO","PER","Listen to the spell's echoes and identify which words sustain the illusion.",20,"You name the false phrase and Arthur cuts through it.","Morgana changes the cadence and conceals the binding word.",112,49,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),

  c("DUNE_GIEDI_ARENA","BREAK_BLADE","STR","Trap Feyd's poisoned blade and break it against the arena stone.",24,"The blade snaps and Paul closes on the exposed champion.","Feyd twists free and turns the poison edge toward you.",120,50,"ENEMY_DEBUFF",1,0,0.02,"Arena strength."),
  c("DUNE_GIEDI_ARENA","CONTROL_BREATH","END","Control your breathing and resist the poison mist around the fighting pit.",23,"You remain steady and keep Paul clear of the contaminated air.","The poison clouds your reactions.",118,50,"ALLY_BUFF",2,9,0,"Endurance against poison."),
  c("DUNE_GIEDI_ARENA","CROSS_SHADOW","AGI","Move through the black sun's shadow and attack from Feyd's blind side.",22,"You cross unseen and force Feyd to divide his guard.","The arena lights shift and expose you midway.",116,52,"FIRST_STRIKE",1,0,0.03,"Agility route."),
  c("DUNE_GIEDI_ARENA","TRUST_VISION","LCK","Act on a fragment of possible future and trust that this is the right path.",25,"The moment unfolds as foreseen and Feyd enters Paul's reach.","The vision belongs to another possibility and leaves you exposed.",130,58,"COMBAT_ADVANTAGE",2,0,0.07,"High-risk prescient gamble."),
  c("DUNE_GIEDI_ARENA","READ_POISON_HAND","PER","Watch Feyd's hands and identify which blade carries the poison.",21,"You expose the poisoned feint and warn Paul before it lands.","Feyd switches blades inside the motion.",118,51,"ENEMY_DEBUFF",1,0,0.02,"Perception is favored."),
];

const scenes = workbook.worksheets.getItem("Scenes");
const choices = workbook.worksheets.getItem("SceneChoices");
const scenesStart = scenes.getUsedRange(true).rowCount + 1;
const choicesStart = choices.getUsedRange(true).rowCount + 1;
scenes.tables.getItem("ScenesTable").rows.add(null, scenesRows);
choices.tables.getItem("SceneChoicesTable").rows.add(null, choicesRows);

scenes.getRange(`A${scenesStart}:T${scenesStart + scenesRows.length - 1}`).format = { font: { typeface: "Calibri", fontSize: 9 }, verticalAlignment: "top", wrapText: true, rowHeight: 48 };
choices.getRange(`A${choicesStart}:P${choicesStart + choicesRows.length - 1}`).format = { font: { typeface: "Calibri", fontSize: 9 }, verticalAlignment: "top", wrapText: true, rowHeight: 48 };
scenes.getRange(`H${scenesStart}:J${scenesStart + scenesRows.length - 1}`).format.numberFormat = "0";
scenes.getRange(`O${scenesStart}:P${scenesStart + scenesRows.length - 1}`).format.numberFormat = "0%";
scenes.getRange(`Q${scenesStart}:R${scenesStart + scenesRows.length - 1}`).format.numberFormat = "0";
choices.getRange(`E${choicesStart}:E${choicesStart + choicesRows.length - 1}`).format.numberFormat = "0";
choices.getRange(`H${choicesStart}:I${choicesStart + choicesRows.length - 1}`).format.numberFormat = "0";
choices.getRange(`O${choicesStart}:O${choicesStart + choicesRows.length - 1}`).format.numberFormat = "0%";

const sceneCheck = await workbook.inspect({ kind: "table", sheetId: "Scenes", range: `A${scenesStart}:T${scenesStart + scenesRows.length - 1}`, include: "values,formulas", tableMaxRows: 20, tableMaxCols: 20, maxChars: 16000 });
const choiceCheck = await workbook.inspect({ kind: "table", sheetId: "SceneChoices", range: `A${choicesStart}:P${choicesStart + 9}`, include: "values,formulas", tableMaxRows: 12, tableMaxCols: 16, maxChars: 9000 });
const errors = await workbook.inspect({ kind: "match", searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A", options: { useRegex: true, maxResults: 300 }, summary: "final formula error scan" });
console.log(sceneCheck.ndjson);
console.log(choiceCheck.ndjson);
console.log(errors.ndjson);

const outputDir = "C:/Users/charl/OneDrive/Desktop/bbsgame/outputs/019fc439-d617-7783-a9b4-5347c2d0bf25";
await fs.mkdir(outputDir, { recursive: true });
const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(`${outputDir}/GameContent_Perks_Worldbosses_with_Scenes.xlsx`);
await output.save(sourcePath);
console.log(`Added ${scenesRows.length} scenes and ${choicesRows.length} choices.`);
